ALTER TABLE Paciente ALTER COLUMN CPF DROP NOT NULL;
ALTER TABLE Paciente ALTER COLUMN Queixa_Principal DROP NOT NULL;
ALTER TABLE Paciente ALTER COLUMN Historia_Molestia_Pregressa DROP NOT NULL;

ALTER TABLE Paciente ADD COLUMN Observacao TEXT;