spring:
  datasource:
    url: jdbc:postgresql://db-server/aproove-dbname

  security:
    oauth2:
      client:
        registration:
          "[com.github.andrepenteado.roove]":
            provider: com.github.andrepenteado.sso.portal
            client-name: AProove
            client-id: LOCAL-roove
            client-secret: ***REMOVED***
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_basic
        provider:
          "[com.github.andrepenteado.sso.portal]":
            issuer-uri: https://login.apcode.com.br

management:
  tracing:
    export:
      enabled: false

frontend:
  pagina-inicial: http://localhost:4200/roove/pagina-inicial